[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "cd packages/frontend && npm run build && cd ../..",
  "cd packages/backend && npx tsc --skipLibCheck && cd ../..",
  "npx prisma generate --schema=packages/backend/prisma/schema.prisma"
]

[start]
cmd = "npx prisma migrate deploy --schema=packages/backend/prisma/schema.prisma && npx tsx packages/backend/prisma/seed.ts; node packages/backend/dist/index.js"
